# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-30 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='measurements',
            field=models.ManyToManyField(blank=True, help_text='Which measurements is the club using? Be aware of units (cm, inch, ...)!', to='performance.Measurement'),
        ),
        migrations.AddField(
            model_name='club',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
