# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='bioage_method',
            field=models.CharField(choices=[('PHV', 'PHV'), ('pre', 'Height Prediction'), ('best', 'best')], default='best', help_text='Which method should be used to calculate the bio age?', max_length=10),
        ),
    ]