# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170329_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='invited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
