# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_player_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('da', 'Danish'), ('de', 'German')], default='en', max_length=7),
        ),
    ]
