# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_club_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='club',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('da', 'Danish')], default='en', max_length=7),
        ),
    ]
