# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-30 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('profile', '0001_initial'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khamisroche',
            name='current_height',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Height'),
        ),
        migrations.AddField(
            model_name='khamisroche',
            name='current_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Weight'),
        ),
        migrations.AddField(
            model_name='khamisroche',
            name='parents_height',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.ParentsHeight'),
        ),
        migrations.AddField(
            model_name='khamisroche',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player'),
        ),
    ]
