# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-30 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='category',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
