# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-05 15:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_measurement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='category',
            field=models.CharField(default='test', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='slug_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
