# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 10:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20170105_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Arbitrary Json Field'),
        ),
    ]
