# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-30 15:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('genetics', '0001_initial'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_age', models.DecimalField(decimal_places=10, max_digits=20)),
                ('slope_to_bio_age', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('height', django_measurement.models.MeasurementField(measurement_class='Distance')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
            ],
        ),
        migrations.CreateModel(
            name='ParentsHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fathers_height', django_measurement.models.MeasurementField(measurement_class='Distance')),
                ('mothers_height', django_measurement.models.MeasurementField(measurement_class='Distance')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PredictedHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('predicted_height', django_measurement.models.MeasurementField(measurement_class='Distance')),
                ('method', models.CharField(choices=[('dna', 'DNA Test'), ('khr', 'Khamis Roche')], max_length=10)),
                ('dna_height', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genetics.DnaHeight')),
                ('khamis_roche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.KhamisRoche')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('weight', django_measurement.models.MeasurementField(measurement_class='Mass')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
            ],
        ),
        migrations.AddField(
            model_name='bioage',
            name='current_height',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Height'),
        ),
        migrations.AddField(
            model_name='bioage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player'),
        ),
        migrations.AddField(
            model_name='bioage',
            name='predicted_height',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.PredictedHeight'),
        ),
    ]
