# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-05 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161230_1502'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phv_date', models.DateField()),
                ('current_height', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Height')),
                ('current_weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Weight')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
            ],
        ),
        migrations.CreateModel(
            name='SittingHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('sitting_height', django_measurement.models.MeasurementField(measurement_class='Distance')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
            ],
        ),
        migrations.AddField(
            model_name='phv',
            name='sitting_height',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.SittingHeight'),
        ),
    ]
