# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-05 19:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20170105_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='phv',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 5, 19, 48, 55, 276519, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
