# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20170126_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyFat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('body_fat', models.DecimalField(decimal_places=3, max_digits=4, validators=[profile.models.valid_pct])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
            ],
        ),
    ]
