# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('unit', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('upper_limit', models.DecimalField(decimal_places=10, max_digits=16)),
                ('lower_limit', models.DecimalField(decimal_places=10, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=16)),
                ('date', models.DateField(auto_now_add=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Measurement')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='coach',
            field=models.ManyToManyField(blank=True, to='dashboard.Coach'),
        ),
        migrations.AddField(
            model_name='performance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Player'),
        ),
    ]
