# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160318_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'permissions': (('read_car', 'Can read Car'),)},
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
