# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160319_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={},
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(),
        ),
    ]
