# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160320_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
