# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_performance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
