# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_player_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
