# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20160328_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='lab_key',
        ),
    ]
