# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-30 15:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnaHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('predicted_height', django_measurement.models.MeasurementField(measurement_class='Distance')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('original_filename', models.CharField(max_length=2000)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
            ],
        ),
    ]
