# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 12:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_club_bio_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(help_text='The player who supplied this answer', on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField()),
                ('value', models.CharField(max_length=64, verbose_name='Short Value')),
                ('text', models.CharField(max_length=200, verbose_name='Choice Text')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('question_type', models.CharField(choices=[('choice-yesno', 'Choice: Yes or No'), ('choice-yesnocomment', 'Choice & Comment: Yes or No or Whaaa?'), ('open', 'Open: A simple one line input box'), ('open-textfield', 'Textfield: A box for lengthy answers'), ('choice', 'Choice: A list of choices to choose from'), ('choice-freeform', 'Choice & Free Form: A list of choices with a chance to enter something else'), ('choice-multiple', 'Multiple Choice: A list of choices with multiple answers'), ('choice-multiple-freeform', 'Multiple Choice & Free Form: Multiple Answers with multiple user defined answers'), ('range', 'Range: A range of number from which one number can be chosen'), ('number', 'Number: A number'), ('comment', 'Not a question, but only a comment displayed to the user')], max_length=50)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('footer', models.TextField(blank=True, help_text='Footer rendered below the question interpreted as textile', verbose_name='Footer')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'English'), ('da', 'Danish'), ('de', 'German')], default='en-us', max_length=2, verbose_name='Language')),
                ('club', models.ManyToManyField(blank=True, to='accounts.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=64)),
                ('sort', models.IntegerField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Section'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='The question that this is an answer to', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question'),
        ),
    ]
