# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sort',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
