# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_questionnaire_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
