# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170329_1126'),
        ('questionnaire', '0006_auto_20170317_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(help_text='The player who supplied this answer', on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='player',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice-yesno', 'Choice: Yes or No'), ('choice-yesnocomment', 'Choice & Comment: Yes or No with a chance to comment on the answer'), ('open', 'Open: A simple one line input box'), ('open-textfield', 'Textfield: A box for lengthy answers'), ('choice', 'Choice: A list of choices to choose from'), ('choice-freeform', 'Choice & Free Form: A list of choices with a chance to enter something else'), ('choice-multiple', 'Multiple Choice: A list of choices with multiple answers'), ('choice-multiple-freeform', 'Multiple Choice & Free Form: Multiple Answers with multiple user defined answers'), ('range', 'Range: A range of options from which can be chosen'), ('number', 'Number: A number'), ('comment', 'Comment: Not a question, but only a comment displayed to the user')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, help_text='Is field required to answer?'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.QuestionnaireSubmission'),
            preserve_default=False,
        ),
    ]
