# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20170331_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionnaireSubmission',
            new_name='Submission',
        ),
    ]
