# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20170407_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(),
        ),
    ]
