# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20170427_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
