# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20170504_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.CharField(max_length=64, verbose_name='Coach Text'),
        ),
    ]
